w3c-cg/webagents

- README.md
I struggled a bit trying to find the TPAC events, so a small PR.
> Add calendar information to readme

- charters/webagents-cg-2023-draft.html
Together with @aricci303 and @Antoine-Zimmermann, we invite all members of the WebAgents CG to review the first draft of the CG charter. Please submit your feedback by commenting on this PR.
We thank @smnmyr for his initial review of this charter draft.
> First draft of the WebAgents CG charter

- TaskForces/ManageableAffordance/Readme.md
This is the initial description for the new task force. This is reviewed by the co-chairs and is ready to accept feedback.
> Manageable Affordances Task Force description

- .github/ISSUE_TEMPLATE/use_case.md
- TaskForces/UseCases/README.md
Initial text for the UC TF of the WebAgents CG.
> Use Cases Task Force description

- Meetings/RegularMeetings/2024-02-15.md
These are the meeting notes from the regular meeting of the WebAgents CG on 15.02.2024.
> Add regular meeting notes from 15.02.2024

- Meetings/RegularMeetings/2024-02-26.md
Meeting notes for the regular bi-weekly meeting.
> add Regular Meeting Notes: 2024-02-26

- Meetings/RegularMeetings/2024-03-14.md
These are the meeting notes from the regular meeting of the WebAgents CG on 14.03.2024.
> Add regular meeting notes from 14.03.2024

- Meetings/RegularMeetings/2024-03-25.md
These are the meeting notes from the regular meeting of the WebAgents CG on 25.03.2024.
> Add regular meeting notes from 25.03.2024

- Meetings/RegularMeetings/2024-04-11.md
These are the meeting notes from the regular meeting of the WebAgents CG on 11.04.2024.
> Add regular meeting notes from 11.04.2024

- TaskForces/ManageableAffordance/Reports/report-ma-gap-analysis.html
The first version without any content.
> Manageable Affordance TF report

- Meetings/RegularMeetings/2024-04-22.md
These are the meeting notes from the regular meeting of the WebAgents CG on 22.04.2024.
> Add regular meeting notes from 22.04.2024

- Meetings/RegularMeetings/2024-06-06.md
These are the meeting notes from the regular meeting of the WebAgents CG on 06.06.2024.
> Add regular meeting notes from 06.06.2024

- Meetings/RegularMeetings/2024-07-15.md
These are the meeting notes from the regular meeting of the WebAgents CG on 15.07.2024.
> Add regular meeting notes from 15.07.2024

- TaskForces/ManageableAffordance/Requirements.md
I have realised that we still link to a [closed issue](https://github.com/w3c-cg/webagents/issues/34). Better to link to something in the repo.
> Requirements Template for Manageable Affordances Submissions 

- TaskForces/ManageableAffordance/Readme.md
> Workflow for Manageable Affordances Report

- Meetings/RegularMeetings/2024-08-01.md
These are the meeting notes from the regular meeting of the WebAgents CG on 01.08.2024.
> Add regular meeting notes from 01.08.2024

- Meetings/RegularMeetings/2024-10-17/2024-10-17.md
These are the meeting notes from the regular meeting of the WebAgents CG on 17.10.2024.
> Add regular meeting notes from 17.10.2024

- TaskForces/Interoperability/README.md
This is the initial description of the new Interoperability Task Force. The co-chairs approved the task force, and the description is ready for feedback.
> Add initial description for the Interoperability Task Force

- Meetings/RegularMeetings/2025-04-11.md
These are the meeting notes from the regular meeting of the WebAgents CG on 11.04.2025.
> Add regular meeting notes from 11.04.2025

- README.md
- TaskForces/Interoperability/Reports/report-interoperability.html
This PR contains the initial structure for the Interoperability TF report as discussed in the regular meeting on 09.05.2025. I am merging the report draft into the main branch to share it more easily via GitHub Pages.
> Initial structure for the Interoperability TF report

- Meetings/RegularMeetings/2025-05-09.md
These are the meeting notes from the regular meeting of the WebAgents CG on 09.05.2025.
> Add regular meeting notes from 09.05.2025

- Meetings/RegularMeetings/2025-05-19.md
These are the meeting notes from the regular meeting of the WebAgents CG on 19.05.2025.
> Add regular meeting notes from 19.05.2025

- Meetings/RegularMeetings/2025-07-04.md
These are the meeting notes from the regular meeting of the WebAgents CG on 04.07.2025.
> Add regular meeting notes from 04.07.2025

- Meetings/RegularMeetings/2025-08-01.md
These are the meeting notes from the regular meeting of the WebAgents CG on 01.08.2025.
> Add regular meeting notes from 01.08.2025
